#!/usr/bin/env bash

pushd o2data_model &> /dev/null

curl \
-O https://raw.githubusercontent.com/AliceO2Group/AliceO2/dev/Framework/Core/include/Framework/DataTypes.h \
-O https://raw.githubusercontent.com/AliceO2Group/AliceO2/dev/Framework/Core/include/Framework/AnalysisDataModel.h \
-O https://raw.githubusercontent.com/AliceO2Group/AliceO2/dev/Framework/Core/include/Framework/ASoA.h \
-O https://raw.githubusercontent.com/AliceO2Group/AliceO2/dev/Framework/Core/include/Framework/ASoAHelpers.h

popd &> /dev/null

